name: CI
on: [push, pull_request]
jobs:
  lint_lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install tooling
        run: |
          npm init -y
          npm install eslint @lhci/cli -D
          npx eslint **/*.js

      - name: Lighthouse CI
        run: |
          npx lhci autorun \
            --collect.url=https://${{ github.repository_owner }}.github.io/HJMOPS-Ops/ \
            --assert.preset=lighthouse:recommended
